addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.4.2")
addSbtPlugin("com.snowplowanalytics"     % "sbt-snowplow-release" % "0.3.1")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.11.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"         % "1.0.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"           % "5.10.0")
